# Generated by Django 3.1.14 on 2022-10-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20221013_1620'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traintest',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='from_city', to='cities.city', verbose_name='Из какого города'),
        ),
    ]
